CREATE DATABASE u968512456_sauta;

USE u968512456_sauta;

CREATE TABLE GARCOM (
ID_GARCOM int PRIMARY KEY auto_increment,
ENDERECO_FOTO varchar(100),
NOME_GARCOM varchar(40) not null
);

CREATE TABLE TIPO_PAUSA (
ID_TIPO_PAUSA int PRIMARY KEY auto_increment,
NOME_PAUSA varchar(20) not null
);

CREATE TABLE INTERRUPCOES_JORNADA (
ID_PAUSA int PRIMARY KEY auto_increment,
DATA date not null,
DATA_FIM date,
INICIO time not null,
FIM time,
ID_TIPO_PAUSA int not null,
ID_GARCOM int not null,
FOREIGN KEY(ID_GARCOM) REFERENCES GARCOM (ID_GARCOM),
FOREIGN KEY(ID_TIPO_PAUSA) REFERENCES TIPO_PAUSA (ID_TIPO_PAUSA)
);

CREATE TABLE DISPONIBILIDADE (
ID_DISPONIBILIDADE int PRIMARY KEY auto_increment,
DATA_INICIO date not null,
DATA_FIM date,
INICIO time not null,
FIM time,
ID_GARCOM int not null,
FOREIGN KEY(ID_GARCOM) REFERENCES GARCOM (ID_GARCOM)
);

CREATE TABLE CLIENTE (
ID_CLIENTE int PRIMARY KEY auto_increment,
CPF varchar(11) not null unique,
NOME_CLIENTE varchar(40) not null,
DATA_NASCIMENTO date not null,
EMAIL varchar(80) not null
);

CREATE TABLE TELEFONE (
ID_TELEFONE int PRIMARY KEY auto_increment,
TELEFONE varchar(11) not null,
ID_CLIENTE int not null,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE MESA (
ID_MESA int PRIMARY KEY auto_increment,
NUMERO_LUGARES int not null
);

CREATE TABLE RESERVA (
ID_RESERVA int PRIMARY KEY auto_increment,
DATA date not null,
HORARIO time not null,
ID_CLIENTE int not null,
ID_MESA int not null,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY(ID_MESA) REFERENCES MESA(ID_MESA)
);

CREATE TABLE CLIENTE_MESA (
ID_CLIENTE_MESA int PRIMARY KEY auto_increment,
DATA date not null,
DATA_FIM date,
HORARIO time not null,
HORARIO_FIM time,
ID_CLIENTE int not null,
ID_MESA int not null,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY(ID_MESA) REFERENCES MESA (ID_MESA)
);

CREATE TABLE PEDIDO (
ID_PEDIDO int PRIMARY KEY auto_increment,
DATA date not null,
DATA_FIM date,
HORARIO time not null,
HORARIO_FIM time,
HORARIO_AGENDAMENTO time not null,
OBSERVACAO varchar(200),
PRONTO boolean,
ATENDIDO time,
ID_GARCOM int,
ID_CLIENTE_MESA int not null,
FOREIGN KEY(ID_CLIENTE_MESA) REFERENCES CLIENTE_MESA (ID_CLIENTE_MESA),
FOREIGN KEY(ID_GARCOM) REFERENCES GARCOM(ID_GARCOM)
);

CREATE TABLE TIPO_PRATO (
ID_TIPO_PRATO int PRIMARY KEY auto_increment,
TIPO_PRATO varchar(20) not null
);

CREATE TABLE TIPO_BEBIDA (
ID_TIPO_BEBIDA int PRIMARY KEY auto_increment,
TIPO_BEBIDA varchar(20) not null
);

CREATE TABLE PRATO (
ID_PRATO int PRIMARY KEY auto_increment,
PRATO varchar(30) not null,
INGREDIENTES varchar(300),
TEMPO_PREPARO time,
ID_TIPO_PRATO int not null,
FOREIGN KEY(ID_TIPO_PRATO) REFERENCES TIPO_PRATO (ID_TIPO_PRATO)
);

CREATE TABLE BEBIDA (
ID_BEBIDA int PRIMARY KEY auto_increment,
BEBIDA varchar(30) not null,
ALCOOLICA int not null,
TEMPO_PREPARO time,
ID_TIPO_BEBIDA int not null,
FOREIGN KEY(ID_TIPO_BEBIDA) REFERENCES TIPO_BEBIDA (ID_TIPO_BEBIDA)
);

CREATE TABLE PEDIDO_PRATO (
ID_PEDIDO_PRATO int PRIMARY KEY auto_increment,
QUANTIDADE int not null,
OBSERVACAO varchar(300),
ID_PEDIDO int not null,
ID_PRATO int not null,
FOREIGN KEY(ID_PRATO) REFERENCES PRATO (ID_PRATO),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PEDIDO_BEBIDA (
ID_PEDIDO_BEBIDA int PRIMARY KEY auto_increment,
QUANTIDADE int not null,
OBSERVACAO varchar(300),
ID_PEDIDO int not null,
ID_BEBIDA int not null,
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
FOREIGN KEY(ID_BEBIDA) REFERENCES BEBIDA (ID_BEBIDA)
);