-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE GARCOM (
ID_GARCOM int PRIMARY KEY,
ENDERECO_FOTO varchar(100),
NOME_GARCOM varchar(40)
)

CREATE TABLE INTERRUPCOES_JORNADA (
ID_PAUSA int PRIMARY KEY,
DATA date,
INICIO time,
FIM time,
TIPO_PAUSA int,
ID_GARCOM int,
FOREIGN KEY(ID_GARCOM) REFERENCES GARCOM (ID_GARCOM)
)

CREATE TABLE TIPO_PAUSA (
ID_TIPO_PAUSA int PRIMARY KEY,
NOME_PAUSA varchar(20)
)

CREATE TABLE DISPONIBILIDADE (
ID_DISPONIBILIDADE int PRIMARY KEY,
INICIO time,
FIM time,
ID_GARCOM int,
FOREIGN KEY(ID_GARCOM) REFERENCES GARCOM (ID_GARCOM)
)

CREATE TABLE ATENDIMENTO (
ID_ATENDIMENTO int PRIMARY KEY,
INICIO time,
FIM time,
ID_PEDIDO int,
ID_GARCOM int,
FOREIGN KEY(ID_GARCOM) REFERENCES GARCOM (ID_GARCOM)
)

CREATE TABLE PEDIDO_BEBIDA (
ID_PEDIDO_BEBIDA int PRIMARY KEY,
QUANTIDADE int,
OBSERVACAO varchar(300),
ID_PEDIDO int,
ID_BEBIDA int
)

CREATE TABLE TELEFONE (
ID_TELEFONE int PRIMARY KEY,
TELEFONE varchar(11),
ID_CLIENTE int
)

CREATE TABLE RESERVA (
ID_RESERVA int PRIMARY KEY,
DATA date,
HORARIO time,
ID_CLIENTE int
)

CREATE TABLE CLIENTE (
ID_CLIENTE int PRIMARY KEY,
CPF varchar(11),
NOME_CLIENTE varchar(40),
DATA_NASCIMENTO date,
EMAIL varchar(80)
)

CREATE TABLE RESERVA_MESA (
ID_CLIENTE int,
ID_RESERVA int,
ID_MESA int,
PRIMARY KEY(ID_CLIENTE,ID_RESERVA),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY(ID_RESERVA) REFERENCES RESERVA (ID_RESERVA)
)

CREATE TABLE PRATO (
ID_PRATO int PRIMARY KEY,
PRATO varchar(30),
INGREDIENTES varchar(300),
TEMPO_PREPARO time,
ID_TIPO_PRATO int
)

CREATE TABLE TIPO_PRATO (
ID_TIPO_PRATO int PRIMARY KEY,
TIPO_PRATO varchar(20)
)

CREATE TABLE PEDIDO_PRATO (
ID_PEDIDO_PRATO int PRIMARY KEY,
QUANTIDADE int,
OBSERVACAO varchar(300),
ID_PEDIDO int,
ID_PRATO int,
FOREIGN KEY(ID_PRATO) REFERENCES PRATO (ID_PRATO)
)

CREATE TABLE BEBIDA (
ID_BEBIDA int PRIMARY KEY,
BEBIDA varchar(30),
ALCOOLICA int,
TEMPO_PREPARO time,
ID_TIPO_BEBIDA int
)

CREATE TABLE TIPO_BEBIDA (
ID_TIPO_BEBIDA int PRIMARY KEY,
TIPO_BEBIDA varchar(20)
)

CREATE TABLE PEDIDO (
ID_PEDIDO int PRIMARY KEY,
DATA date,
HORARIO time,
HORARIO_AGENDAMENTO time,
OBSERVACAO varchar(200),
ID_CLIENTE_MESA int
)

CREATE TABLE CLIENTE_MESA (
ID_CLIENTE_MESA int PRIMARY KEY,
DATA date,
HORARIO time,
ID_CLIENTE int,
ID_MESA int,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
)

CREATE TABLE MESA (
ID_MESA int PRIMARY KEY,
NUMERO_LUGARES int
)

ALTER TABLE INTERRUPCOES_JORNADA ADD FOREIGN KEY(TIPO_PAUSA) REFERENCES TIPO_PAUSA (ID_TIPO_PAUSA)
ALTER TABLE ATENDIMENTO ADD FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
ALTER TABLE PEDIDO_BEBIDA ADD FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
ALTER TABLE PEDIDO_BEBIDA ADD FOREIGN KEY(ID_BEBIDA) REFERENCES BEBIDA (ID_BEBIDA)
ALTER TABLE TELEFONE ADD FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
ALTER TABLE RESERVA ADD FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
ALTER TABLE RESERVA_MESA ADD FOREIGN KEY(ID_MESA) REFERENCES MESA (ID_MESA)
ALTER TABLE PRATO ADD FOREIGN KEY(ID_TIPO_PRATO) REFERENCES TIPO_PRATO (ID_TIPO_PRATO)
ALTER TABLE PEDIDO_PRATO ADD FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
ALTER TABLE BEBIDA ADD FOREIGN KEY(ID_TIPO_BEBIDA) REFERENCES TIPO_BEBIDA (ID_TIPO_BEBIDA)
ALTER TABLE PEDIDO ADD FOREIGN KEY(ID_CLIENTE_MESA) REFERENCES CLIENTE_MESA (ID_CLIENTE_MESA)
ALTER TABLE CLIENTE_MESA ADD FOREIGN KEY(ID_MESA) REFERENCES MESA (ID_MESA)
